### ISSUE TITLE
Request port to GoLand

### ISSUE THREAD

**Issue by IdlePhysicist** [ocadaruma/tlaplus-intellij-plugin#26]
Hello, I am a GoLand user and I am wondering if it would be possible for this plugin to be ported to the GoLand IDE and presumably other IntelliJ IDEs?

Thanks

**Comment by ocadaruma** [comment]
Currently this plugin depends on IntelliJ platform's java feature to run TLC (https://github.com/ocadaruma/tlaplus-intellij-plugin/blob/v0.7.3/src/main/resources/META-INF/plugin.xml#L25) but yeah, it sounds reasonable to make it works also on other IDEs.
Let me consider if it's possible.

**Comment by ocadaruma** [comment]
https://github.com/ocadaruma/tlaplus-intellij-plugin/releases/tag/v0.7.4 has been released.
Now all IntelliJ-based IDEs (including GoLand) is now supported.

Please try it out

**Comment by IdlePhysicist** [comment]
It looks good, this is the only strange thing that I note. Though it does not impede me using your plugin.

```
Please run the Java VM, which executes TLC with a throughput optimized garbage collector, by passing the "-XX:+UseParallelGC" property.
```

Thank you for doing this work!

**Comment by ocadaruma** [comment]
Ah yeah, that's a known warning message because G1GC is used by default now.
I think it shouldn't cause any actual problem.
