### ISSUE TITLE
Add Run-Option to configure the number of workers used

### ISSUE THREAD

**Issue by crazy-weasel** [ocadaruma/tlaplus-intellij-plugin#29]
Hi!

Thanks for the plugin. It's nice to work within IntelliJ instead of the TLA Toolbox.

One thing I'm really missing is the ability to specify the number of used workers. (tlc option -workers) The default of tlc is just 1.

Thanks

**Comment by ocadaruma** [comment]
Thanks for reporting the issue!

Sounds nice to have indeed. let me try

**Comment by ocadaruma** [comment]
Will be released in 0.8.0
