### ISSUE TITLE
Update the plugin to IntelliJ 2023

### ISSUE THREAD

**Issue by alexd6631** [ocadaruma/tlaplus-intellij-plugin#31]
Hello,

It seems the plugin is no longer compatible with the 2023 versions of Jetbrains IDE, which were recently released.

Is there any plan to update it ?

Thanks

**Comment by ocadaruma** [comment]
Oh thanks for reporting.

Yeah let me check

**Comment by ocadaruma** [comment]
The plugin has been approved.

**Comment by alexd6631** [comment]
Thanks for the quick update, the plugin works like a charm so far.

**Comment by alexd6631** [comment]
Hello @ocadaruma,

It seems the plugin is no longer compatible with Webstorm 2023.2

**Comment by ocadaruma** [comment]
Oh thank you the notice. I'll handle soon.

Maybe I should have something to detect new-ver automatically

**Comment by ocadaruma** [comment]
@alexd6631 New ver is published as `0.9.1`. Will be available on marketplace within few days
